name: Release

on:
  push:
    tags:
      - '*.*.*'
      
jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        activate-environment: hybracterENV
        environment-file: build/environment.yaml
        auto-activate-base: false
        miniforge-version: latest # not mambaforge anymore
        channels: conda-forge,bioconda,defaults
        auto-update-conda: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package to Pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}